spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
server:
  port: 8084
  forward-headers-strategy: framework
  servlet:
    context-path: /auth



jwt:
  secret: ${JWT_SECRET}
  duration: 3600000