
spring:
  rabbitmq:
    addresses: ${RABBITMQ_URL}
    ssl:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: notification-service

brevo:
    api-key: ${BREVO_API_KEY}
    sender-email: ${BREVO_SENDER_EMAIL}
    sender-name: ${BREVO_SENDER_NAME}
    base-url: ${BREVO_API_URL}