spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  rabbitmq:
    addresses: ${RABBITMQ_URL}
    ssl:
      enabled: true

brevo:
    api-key: ${BREVO_API_KEY}
    sender-email: ${BREVO_SENDER_EMAIL}
    sender-name: ${BREVO_SENDER_NAME}
    base-url: ${BREVO_API_URL}