spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderflow?currentSchema=notification
    username: orderflow
    password: orderflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: notification
    show-sql: false

  flyway:
    schemas:
      - notification
    default-schema: notification
    locations: classpath:db/migration/notification
    baseline-on-migrate: false

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: notification-service
