spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://order-service:8081}
          predicates:
            - Path=/orders/**

        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://inventory-service:8082}
          predicates:
            - Path=/inventory/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8083}
          predicates:
            - Path=/notifications/**

        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8084}
          predicates:
            - Path=/auth/**

        - id: web
          uri: ${WEB_SERVICE_URL:http://web:8085}
          predicates:
            - Path=/buy,/login,/register,/verifycode,/resend-code,/dashboard,/catalog,/css/**,/logout

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info