spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory/**
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/notifications/**
        - id: auth-service
          uri: http://auth-service:8084
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
