spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
        - id: web
          uri: http://localhost:8085
          predicates:
            - Path=/buy,/login,/register,/verifycode,/resend-code,/dashboard,/catalog,/css/**,/logout

management:
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
