global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/orders/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8081']

  - job_name: 'inventory-service'
    metrics_path: '/inventory/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8083']

  - job_name: 'auth-service'
    metrics_path: '/auth/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8084']

  - job_name: 'payment-service'
    metrics_path: '/payment/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8086']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['orderflow-gateway:8080']